### ISSUE TITLE
In schemas, for properties that are enums, the presence of a 'type' field in inconsisent

### ISSUE THREAD

**Issue by majensen** [NCI-GDC/gdcdictionary#141]
Presumably all enums are of type 'string', but sometimes a property that is an enum does not also have a field "type => string". Many examples, but compare sample:tumor_code_id and sample:tumor_descriptor. My suggestion is for enums to be type "enum". 
@dmiller15 @allisonheath

**Comment by dmiller15** [comment]
I've made a PR to get rid of the instances of `type: string` where an `enum` is present. Those seemed to be in the older nodes (sample, annotation, and tag) so I can't really give any insight as to why they were there. We'll probably need to make sure this doesn't adversely affect data import before merging. I'm not entirely sure if the `enum` overrides the `type: string` or the other way around.
