### ISSUE TITLE
Hello from JSON Schema

### ISSUE THREAD

**Issue by Relequestual** [NCI-GDC/gdcdictionary#631]
Hi
I'm part of the JSON Schema team.
My day job involves working on GA4GH standards.
I'm glad to find another repository containing many JSON Schema files!

I thought I'd open the lines of communication. The NIH-GDC is already a GA4GH Driver Project, and I know there will be official lines of communication opened at some point, but I wanted to reach out to those working on the schemas today.

I'm curious how you arrived at your process for managing schema changes, as documented at https://github.com/NCI-GDC/gdcdictionary#dictionary-changes. Can you share some information on this please?

Thanks in advance!

As an aside, I'm happy to help with any JSON Schema related issues or questions.
Also, the next version of JSON Schema (draft-8) is going to add some things which you'll find useful!

**Comment by msfitzsimons** [comment]
Hello Relequestual.  Can you please submit a request to support@nci-gdc.datacommons.io with your questions?  We would be happy to discuss our data dictionary and processes with you.

Many thanks
Michael
GDC User Services Team

**Comment by Relequestual** [comment]
Will do. Thanks.
